name: Deploy to GitHub Pages

on:
  # 기본 브랜치에 대한 푸시 이벤트 발생 시 실행
  push:
    branches:
      - main

#   # Actions 탭에서 수동으로 워크플로우를 실행할 수 있도록 구성
#   workflow_dispatch:

# # GITHUB_TOKEN의 권한을 설정하여 GitHub Pages에 배포할 수 있도록 함
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # 동시에 하나의 배포만 허용하도록 구성
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  build:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build # 프로젝트에 맞는 빌드 명령어

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.BLOG_KEY }}
          publish_dir: ./dist
